"""Tailscale-first VPS hardening — LOCAL-ONLY per D2.

Generates a Tailscale hardening script but does NOT execute it.
D2 decision: local-runtime-only. NO real VPS deploy.

The script covers:
  Phase 1: Install Tailscale
  Phase 2: Authenticate with auth key
  Phase 3: Verify Tailscale IP and SSH
  Phase 4: Harden SSH (listen on tailscale0 only)
  Phase 5: UFW rules (allow tailscale0, deny all other incoming)
  Phase 6: Kernel sysctl hardening
  Phase 7: Auto-updates (unattended-upgrades)

Per D2: script is GENERATED/written but NOT executed.
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


class TailscaleHardener:
    """Tailscale-first VPS hardening script generator.

    D2 COMPLIANCE: This class generates hardening scripts but does NOT
    execute them. All VPS deployment is deferred until operator approval.

    Usage:
        hardener = TailscaleHardener()
        script = hardener.generate_hardening_script()
        # Write script to file, review, then execute manually on VPS
    """

    def __init__(
        self,
        tailscale_hostname: str = "guinevere-vps",
        ssh_port: int = 22,
        tailscale_auth_key_env: str = "TAILSCALE_AUTH_KEY",
    ) -> None:
        self.tailscale_hostname = tailscale_hostname
        self.ssh_port = ssh_port
        self.tailscale_auth_key_env = tailscale_auth_key_env

    def generate_hardening_script(self) -> str:
        """Generate the Tailscale hardening bash script.

        Returns the script as a string. Per D2, this is NOT executed
        automatically — it must be reviewed and run manually on the VPS.

        The script:
          1. Installs Tailscale
          2. Authenticates with auth key
          3. Verifies Tailscale IP
          4. Hardens SSH to listen on tailscale0 only
          5. Configures UFW (allow tailscale0, deny other incoming)
          6. Applies kernel sysctl hardening
          7. Enables auto-updates (unattended-upgrades)
        """
        script = f"""#!/usr/bin/env bash
# Tailscale-First VPS Hardening Script
# Generated by guinevere.production.tailscale
# D2 COMPLIANCE: LOCAL-ONLY — DO NOT execute without operator approval
# Tailscale is the FIRST step — all other hardening depends on it

set -euo pipefail

# --- D2 Safety Check ---
if [[ "${{P24_ENVIRONMENT:-}}" != "production" ]]; then
    echo "[D2] P24_ENVIRONMENT is not 'production'. Exiting safely."
    echo "[D2] This script is a design artifact for future VPS deployment."
    echo "[D2] Set P24_ENVIRONMENT=production to proceed (requires operator approval)."
    exit 0
fi

echo "=== Tailscale-First VPS Hardening ==="
echo "Hostname: {self.tailscale_hostname}"
echo "SSH Port: {self.ssh_port}"
echo ""

# --- Phase 1: Install Tailscale ---
echo "[Phase 1] Installing Tailscale..."
curl -fsSL https://tailscale.com/install.sh | sh

# --- Phase 2: Authenticate ---
echo "[Phase 2] Authenticating with Tailscale..."
if [[ -z "${{{self.tailscale_auth_key_env}:-}}" ]]; then
    echo "ERROR: {self.tailscale_auth_key_env} not set. Cannot authenticate."
    exit 1
fi
tailscale up --authkey="${{{self.tailscale_auth_key_env}}}" --hostname={self.tailscale_hostname}

# --- Phase 3: Verify ---
echo "[Phase 3] Verifying Tailscale connectivity..."
TS_IP=$(tailscale ip -4)
if [[ -z "$TS_IP" ]]; then
    echo "ERROR: Could not get Tailscale IP. Authentication may have failed."
    exit 1
fi
echo "Tailscale IP: $TS_IP"
echo "Verify SSH: ssh admin@$TS_IP"

# --- Phase 4: Harden SSH ---
echo "[Phase 4] Hardening SSH configuration..."
SSHD_CONFIG="/etc/ssh/sshd_config"
cp "$SSHD_CONFIG" "$SSHD_CONFIG.bak.$(date +%s)"

# Listen only on Tailscale interface
if ! grep -q "ListenAddress $TS_IP" "$SSHD_CONFIG"; then
    echo "ListenAddress $TS_IP" >> "$SSHD_CONFIG"
fi

# Disable root login
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' "$SSHD_CONFIG"

# Disable password authentication (key-only)
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' "$SSHD_CONFIG"

systemctl restart sshd

# --- Phase 5: UFW Firewall ---
echo "[Phase 5] Configuring UFW firewall (Tailscale-first)..."
apt-get install -y ufw

# Allow SSH on Tailscale interface only
ufw allow in on tailscale0 to any port {self.ssh_port} proto tcp comment "SSH via Tailscale"

# Allow Tailscale UDP (WireGuard)
ufw allow in on tailscale0 to any port 41641 proto udp comment "Tailscale WireGuard"

# Allow established connections
ufw default deny incoming
ufw default allow outgoing

# Enable UFW
echo "y" | ufw enable
ufw status verbose

# --- Phase 6: Kernel Hardening ---
echo "[Phase 6] Applying kernel sysctl hardening..."
cat > /etc/sysctl.d/99-guinevere-hardening.conf << 'SYSCTL'
# IP forwarding (required for Tailscale subnet routing if needed)
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

# ICMP redirects (disable — prevent MITM)
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0

# SYN cookies (DDoS protection)
net.ipv4.tcp_syncookies = 1

# Ignore ICMP broadcasts
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log martian packets
net.ipv4.conf.all.log_martians = 1
SYSCTL
sysctl -p /etc/sysctl.d/99-guinevere-hardening.conf

# --- Phase 7: Auto-Updates ---
echo "[Phase 7] Enabling automatic security updates..."
apt-get install -y unattended-upgrades
dpkg-reconfigure -plow unattended-upgrades

echo ""
echo "=== Hardening Complete ==="
echo "Tailscale IP: $TS_IP"
echo "SSH: ssh admin@$TS_IP (key-only, Tailscale-only)"
echo "UFW: tailscale0 only, all other incoming denied"
echo ""
echo "NEXT STEPS:"
echo "  1. Verify SSH access: ssh admin@$TS_IP"
echo "  2. Test Tailscale connectivity from another device"
echo "  3. Deploy Guinevere application"
"""
        logger.info(
            "tailscale_script_generated",
            hostname=self.tailscale_hostname,
            script_length=len(script),
            d2_compliant=True,
        )
        return script

    def generate_postgres_security_notes(self) -> str:
        """Generate PostgreSQL security configuration notes.

        Returns documentation for securing PostgreSQL on the VPS.
        PostgreSQL must listen on localhost only — remote access via
        SSH tunnel over Tailscale.
        """
        return """# PostgreSQL Security Configuration (Tailscale-First)

## postgresql.conf
listen_addresses = 'localhost'  # NEVER 0.0.0.0

## pg_hba.conf
# Local connections only
host all all 127.0.0.1/32 scram-sha-256
local all all scram-sha-256

## Remote access via SSH tunnel over Tailscale:
# From your local machine:
#   ssh -L 5432:localhost:5432 admin@<tailscale-ip>
# Then connect to localhost:5432

## Redis security
# bind 127.0.0.1
# protected-mode yes
# requirepass <strong-password>
"""

    def health(self) -> dict[str, object]:
        """Return hardener configuration status."""
        return {
            "hostname": self.tailscale_hostname,
            "ssh_port": self.ssh_port,
            "d2_compliant": True,
            "executed": False,
            "note": "Script generated but NOT executed (D2 local-only)",
        }


__all__ = ["TailscaleHardener"]
