"""Self-improvement reflection evaluator for the Living Autonomy Kernel (LK-015).

This module implements the reflection/evaluation domain mind. It inspects
recent loop execution metrics, proposes improvement candidates across four
categories (skill, prompt, planner, code), and provides a regression gate
that must pass before a candidate is promoted.

Hermes brain integration is intentionally a placeholder — real suggestion
generation via the kernel brain will be added in a future iteration.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Literal
from uuid import uuid4

import shlex
import structlog
import subprocess

from guinvere.life_kernel.state import LifeMindState, Priority

if TYPE_CHECKING:
    from langgraph.graph.state import CompiledStateGraph

logger = structlog.get_logger(__name__)


CandidateCategory = Literal["skill", "prompt", "planner", "code"]
"""Category of an improvement candidate."""

CandidateStatus = Literal["proposed", "regression_testing", "promoted", "rejected"]
"""Lifecycle status of an improvement candidate."""


@dataclass
class ImprovementCandidate:
    """A single self-improvement candidate generated by reflection.

    Attributes:
        candidate_id: Unique UUID4 identifier.
        category: Candidate category (skill, prompt, planner, code).
        description: Human-readable description of the proposed improvement.
        source_loop: Identifier of the loop/cycle that produced the candidate.
        priority: Autonomy priority level for the candidate.
        created_at: UTC timestamp when the candidate was created.
        status: Current lifecycle status of the candidate.
        metrics_snapshot: Dict snapshot of the metrics that triggered the candidate.
        rollback_version: Optional version string to roll back to if promoted.
        project_id: Optional project namespace for multi-project context.
    """

    candidate_id: str
    category: CandidateCategory
    description: str
    source_loop: str
    priority: Priority
    created_at: datetime
    status: CandidateStatus
    metrics_snapshot: dict[str, Any]
    rollback_version: str | None
    project_id: str | None = None

    @classmethod
    def new(
        cls,
        *,
        category: CandidateCategory,
        description: str,
        source_loop: str,
        priority: Priority,
        metrics_snapshot: dict[str, Any],
        rollback_version: str | None = None,
        status: CandidateStatus = "proposed",
        project_id: str | None = None,
    ) -> "ImprovementCandidate":
        """Create a new candidate with a generated UUID and current UTC timestamp."""
        return cls(
            candidate_id=str(uuid4()),
            category=category,
            description=description,
            source_loop=source_loop,
            priority=priority,
            created_at=datetime.now(timezone.utc),
            status=status,
            metrics_snapshot=metrics_snapshot,
            rollback_version=rollback_version,
            project_id=project_id,
        )


class ReflectionEvaluator:
    """Evaluate life-mind loop metrics and generate improvement candidates."""

    _ERROR_THRESHOLD: int = 3
    _IDLE_THRESHOLD_SECONDS: float = 3600.0
    _OBSERVATION_CAP: int = 80
    _CYCLE_COUNT_THRESHOLD: int = 100
    _ACT_COUNT_LOW: int = 10

    def __init__(
        self,
        graph: CompiledStateGraph[LifeMindState, Any, Any, Any],
        graph_config: dict[str, Any],
        hermes_brain: Any | None = None,
        project_id: str | None = None,
    ) -> None:
        """Initialise the reflection evaluator.

        Args:
            graph: Compiled life-mind StateGraph.
            graph_config: Configuration dict passed to the graph (e.g. thread_id).
            hermes_brain: Optional Hermes brain for future suggestion generation.
            project_id: Optional project namespace for multi-project context.
        """
        self.graph = graph
        self.graph_config = graph_config
        self.hermes_brain = hermes_brain
        self.project_id = project_id
        logger.info(
            "reflection_evaluator_init",
            graph_config=graph_config,
            has_hermes_brain=hermes_brain is not None,
            project_id=project_id,
        )

    def _source_loop(self) -> str:
        """Return the source loop identifier from graph config."""
        thread_id = self.graph_config.get("thread_id")
        if isinstance(thread_id, str) and thread_id:
            return thread_id
        return "default"

    def evaluate(self, state: LifeMindState) -> list[ImprovementCandidate]:
        """Evaluate loop metrics and return a list of improvement candidates.

        Heuristics:
        - More than 3 errors -> planner improvement candidate.
        - High cycle count with low act count -> planner/efficiency candidate.
        - Idle for more than 1 hour -> skill/curiosity improvement candidate.
        - Observation queue near cap (>80) -> observer/observer optimization candidate.

        Args:
            state: Current life-mind state.

        Returns:
            List of generated improvement candidates.
        """
        candidates: list[ImprovementCandidate] = []

        if self._has_high_errors(state):
            candidates.append(self.generate_planner_candidate(state))

        if self._has_low_efficiency(state):
            candidates.append(self.generate_planner_candidate(state))

        if self._is_idling(state):
            candidates.append(self.generate_skill_candidate(state))

        if self._observation_queue_near_cap(state):
            candidates.append(self.generate_skill_candidate(state))

        if not candidates:
            candidates.append(self.generate_prompt_candidate(state))

        logger.info(
            "reflection_evaluator_evaluated",
            candidate_count=len(candidates),
            source_loop=self._source_loop(),
        )
        return candidates

    def _has_high_errors(self, state: LifeMindState) -> bool:
        errors = state.get("errors", [])
        return len(errors) > self._ERROR_THRESHOLD

    def _has_low_efficiency(self, state: LifeMindState) -> bool:
        cycle_count = state.get("cycle_count", 0)
        act_count = state.get("act_count", 0)
        return (
            cycle_count > self._CYCLE_COUNT_THRESHOLD
            and act_count < self._ACT_COUNT_LOW
        )

    def _is_idling(self, state: LifeMindState) -> bool:
        last_heartbeat = state.get("last_heartbeat")
        if not isinstance(last_heartbeat, str):
            return False
        try:
            last_dt = datetime.fromisoformat(last_heartbeat)
            elapsed = (datetime.now(timezone.utc) - last_dt).total_seconds()
            return elapsed > self._IDLE_THRESHOLD_SECONDS
        except (ValueError, TypeError):
            return False

    def _observation_queue_near_cap(self, state: LifeMindState) -> bool:
        observations = state.get("observations", [])
        return len(observations) > self._OBSERVATION_CAP

    def _metrics_snapshot(self, state: LifeMindState) -> dict[str, Any]:
        return {
            "observation_count": len(state.get("observations", [])),
            "act_count": state.get("act_count", 0),
            "cycle_count": state.get("cycle_count", 0),
            "error_count": len(state.get("errors", [])),
            "current_phase": state.get("current_phase"),
        }

    def generate_skill_candidate(self, state: LifeMindState) -> ImprovementCandidate:
        """Generate a skill improvement candidate (placeholder)."""
        logger.info(
            "generate_skill_candidate_placeholder",
            source_loop=self._source_loop(),
            project_id=self.project_id,
        )
        return ImprovementCandidate.new(
            category="skill",
            description="Skill improvement: add a curiosity-driven micro-task when idling or "
            "when observation queue is near capacity.",
            source_loop=self._source_loop(),
            priority=Priority.IMPROVE_AUTONOMY,
            metrics_snapshot=self._metrics_snapshot(state),
            project_id=self.project_id,
        )

    def generate_prompt_candidate(self, state: LifeMindState) -> ImprovementCandidate:
        """Generate a prompt optimization candidate (placeholder)."""
        logger.info(
            "generate_prompt_candidate_placeholder",
            source_loop=self._source_loop(),
            project_id=self.project_id,
        )
        return ImprovementCandidate.new(
            category="prompt",
            description="Prompt optimization: review reflection prompts for clarity and "
            "actionability during normal operation.",
            source_loop=self._source_loop(),
            priority=Priority.ENGINEERING,
            metrics_snapshot=self._metrics_snapshot(state),
            project_id=self.project_id,
        )

    def generate_planner_candidate(self, state: LifeMindState) -> ImprovementCandidate:
        """Generate a planner enhancement candidate (placeholder)."""
        logger.info(
            "generate_planner_candidate_placeholder",
            source_loop=self._source_loop(),
            project_id=self.project_id,
        )
        return ImprovementCandidate.new(
            category="planner",
            description="Planner enhancement: reduce cycle overhead or error recovery "
            "path in the decide/reflect nodes.",
            source_loop=self._source_loop(),
            priority=Priority.IMPROVE_AUTONOMY,
            metrics_snapshot=self._metrics_snapshot(state),
            project_id=self.project_id,
        )

    def generate_code_candidate(self, state: LifeMindState) -> ImprovementCandidate:
        """Generate a code change candidate (placeholder)."""
        logger.info(
            "generate_code_candidate_placeholder",
            source_loop=self._source_loop(),
            project_id=self.project_id,
        )
        return ImprovementCandidate.new(
            category="code",
            description="Code change: refactor observation reducer or error handling "
            "based on loop metrics.",
            source_loop=self._source_loop(),
            priority=Priority.ENGINEERING,
            metrics_snapshot=self._metrics_snapshot(state),
            project_id=self.project_id,
        )


class RegressionGate:
    """Command-based regression gate for improvement candidates.

    Runs a configurable test command and returns True only if all tests pass.
    """

    def __init__(
        self,
        test_command: str = "python -m pytest tests/life_kernel/ -q --tb=short",
        timeout_s: int = 300,
    ) -> None:
        """Initialise the regression gate.

        Args:
            test_command: Command to run for regression testing. Command string will be split using shlex.
            timeout_s: Maximum seconds to wait for command completion.
        """
        self.test_command = test_command
        self.timeout_s = timeout_s
        logger.info(
            "regression_gate_init",
            test_command=self.test_command,
            timeout_s=self.timeout_s,
        )

    def run_regression_tests(self, candidate: ImprovementCandidate) -> bool:
        """Run regression tests. Returns True only if all tests pass.

        Args:
            candidate: Improvement candidate to test.

        Returns:
            True if tests pass (exit code 0), False otherwise (non-zero exit or timeout).
        """
        logger.info(
            "regression_gate_run_tests",
            candidate_id=candidate.candidate_id,
            category=candidate.category,
            command=self.test_command,
        )
        try:
            result = subprocess.run(
                shlex.split(self.test_command),
                shell=False,
                capture_output=True,
                text=True,
                timeout=self.timeout_s,
            )
            passed = result.returncode == 0
            logger.info(
                "regression_gate_result",
                candidate_id=candidate.candidate_id,
                passed=passed,
                returncode=result.returncode,
            )
            return passed
        except subprocess.TimeoutExpired:
            logger.error(
                "regression_gate_timeout",
                candidate_id=candidate.candidate_id,
                timeout_s=self.timeout_s,
            )
            return False
        except Exception as exc:
            logger.error(
                "regression_gate_error",
                candidate_id=candidate.candidate_id,
                error=str(exc),
            )
            return False

    def promote(self, candidate: ImprovementCandidate) -> bool:
        """Promote a candidate after regression tests pass.

        Args:
            candidate: Improvement candidate to promote.

        Returns:
            True if candidate was promoted (tests passed), False otherwise (tests failed).
        """
        if not self.run_regression_tests(candidate):
            self.rollback(candidate)
            return False
        candidate.status = "promoted"
        logger.info("regression_gate_promote", candidate_id=candidate.candidate_id)
        return True

    def rollback(self, candidate: ImprovementCandidate) -> None:
        """Rollback/reject a candidate after regression tests fail.

        Args:
            candidate: Improvement candidate to rollback.
        """
        logger.info(
            "regression_gate_rollback",
            candidate_id=candidate.candidate_id,
            category=candidate.category,
        )
        candidate.status = "rejected"


class ImprovementTracker:
    """Track improvement candidates in memory (placeholder persistence)."""

    def __init__(self) -> None:
        """Initialise an empty candidate tracker."""
        self._candidates: dict[str, ImprovementCandidate] = {}

    def propose(self, candidate: ImprovementCandidate) -> None:
        """Propose a candidate by storing it in the tracker."""
        self._candidates[candidate.candidate_id] = candidate
        candidate.status = "proposed"
        logger.info(
            "improvement_tracker_propose",
            candidate_id=candidate.candidate_id,
            category=candidate.category,
        )

    def list_by_status(self, status: CandidateStatus) -> list[ImprovementCandidate]:
        """Return all candidates with the given status."""
        return [
            candidate
            for candidate in self._candidates.values()
            if candidate.status == status
        ]

    def get(self, candidate_id: str) -> ImprovementCandidate | None:
        """Return the candidate with the given ID, or None if not found."""
        return self._candidates.get(candidate_id)

    def evaluate_and_propose(
        self,
        evaluator: ReflectionEvaluator,
        state: LifeMindState,
    ) -> list[ImprovementCandidate]:
        """Evaluate state and propose all generated candidates.

        Args:
            evaluator: ReflectionEvaluator instance to use.
            state: Current life-mind state.

        Returns:
            List of proposed candidates.
        """
        candidates = evaluator.evaluate(state)
        for candidate in candidates:
            self.propose(candidate)
        logger.info(
            "improvement_tracker_evaluate_and_propose",
            candidate_count=len(candidates),
        )
        return candidates
