"""Evidence Pipeline — generates and collects evidence artifacts per loop.

Each loop instance gets a structured evidence report summarising all
phase artifacts, LQS score, and timestamps.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import structlog

from guinevere.loops.artifacts import evidence_dir, read_artifact, write_artifact
from guinevere.loops.state_machine import PHASE_NAMES, LoopPhase, LoopStateMachine

logger = structlog.get_logger()

# Map LoopPhase to a filesystem-safe slug for artifact filenames.
_PHASE_SLUGS: dict[LoopPhase, str] = {
    LoopPhase.RESEARCH: "research",
    LoopPhase.PLAN_AND_DELEGATE: "plan-delegate",
    LoopPhase.DELEGATE: "delegate",
    LoopPhase.EXECUTE: "execute",
    LoopPhase.VALIDATE_AND_AUDIT: "validate-audit",
    LoopPhase.UPDATE_DOCUMENTS: "update-documents",
    LoopPhase.SETUP_EVIDENCE: "setup-evidence",
}

# Non-terminal phases that produce artifacts.
_EXECUTION_PHASES = [
    LoopPhase.RESEARCH,
    LoopPhase.PLAN_AND_DELEGATE,
    LoopPhase.DELEGATE,
    LoopPhase.EXECUTE,
    LoopPhase.VALIDATE_AND_AUDIT,
    LoopPhase.UPDATE_DOCUMENTS,
    LoopPhase.SETUP_EVIDENCE,
]


class EvidencePipeline:
    """Manages evidence generation for a loop instance."""

    def __init__(self, loop_id: str) -> None:
        self.loop_id = loop_id
        logger.info(
            "evidence_pipeline.created",
            loop_id=self.loop_id,
        )

    async def collect_phase_artifact(self, phase: LoopPhase, content: str) -> Path:
        """Write phase artifact via artifacts.write_artifact().

        Args:
            phase: The loop phase that produced the artifact.
            content: Markdown content to persist.

        Returns:
            The absolute path to the written artifact file.
        """
        slug = _PHASE_SLUGS.get(phase, f"phase-{phase.value}")
        path = write_artifact(self.loop_id, slug, content)

        logger.info(
            "evidence_pipeline.artifact_collected",
            loop_id=self.loop_id,
            phase=PHASE_NAMES.get(phase, str(phase)),
            path=str(path),
        )

        return path

    async def generate_final_report(self, state: LoopStateMachine) -> str:
        """Generate final evidence-final.md summarising all phases, artifacts, LQS score.

        The report includes loop metadata, all phase artifacts (summarised),
        an LQS (Loop Quality Score) placeholder, and timestamps.

        Args:
            state: The completed (or failed) loop state machine.

        Returns:
            Markdown string of the final evidence report.
        """
        now = datetime.now(timezone.utc)
        artifacts = await self.get_all_artifacts()

        # Build phase summary sections.
        phase_sections: list[str] = []
        for phase in _EXECUTION_PHASES:
            name = PHASE_NAMES[phase]
            slug = _PHASE_SLUGS[phase]
            content = artifacts.get(slug)

            if content is not None:
                # Summarise: first 200 chars as preview.
                preview = content[:200].strip()
                if len(content) > 200:
                    preview += "..."
                phase_sections.append(
                    f"### {name} (Phase {phase.value})\n\n"
                    f"<details><summary>Artifact preview ({len(content)} chars)</summary>\n\n"
                    f"```markdown\n{preview}\n```\n\n</details>"
                )
            else:
                phase_sections.append(
                    f"### {name} (Phase {phase.value})\n\n"
                    f"_No artifact recorded._"
                )

        # LQS (Loop Quality Score) — weighted average placeholder.
        # All weights are 1.0 for now; real scoring deferred to later wave.
        completed_phases = sum(1 for v in artifacts.values() if v is not None)
        total_phases = len(_EXECUTION_PHASES)
        lqs_score = (completed_phases / total_phases * 100.0) if total_phases > 0 else 0.0

        report = f"""\
# Loop Evidence — Final Report

**Loop ID:** `{self.loop_id}`
**Task:** {state.task}
**Goal:** {state.goal or '_No goal specified._'}
**Status:** {state.status.value}
**Final Phase:** {PHASE_NAMES[state.current_phase]}
**Created:** {state.created_at.isoformat()}
**Report Generated:** {now.isoformat()}
**Errors:** {state.error_count}

---

## Loop Quality Score (LQS)

| Metric | Value |
|---|---|
| Completed Phases | {completed_phases}/{total_phases} |
| LQS Score | {lqs_score:.1f}/100 |
| Weights | All 1.0 (placeholder) |

> **Note:** LQS scoring uses weighted average with equal weights (1.0) for all
> phases. Domain-specific weighting and quality metrics will be added in a
> future wave.

---

## Phase Artifacts

{chr(10).join(phase_sections)}

---

## Artifacts Directory

`{evidence_dir(self.loop_id)}`

---

_Report generated by EvidencePipeline for loop `{self.loop_id}`._
"""

        # Persist the final report.
        write_artifact(self.loop_id, "evidence-final", report)

        logger.info(
            "evidence_pipeline.final_report_generated",
            loop_id=self.loop_id,
            lqs_score=lqs_score,
            completed_phases=completed_phases,
            total_phases=total_phases,
            status=state.status.value,
        )

        return report

    async def get_all_artifacts(self) -> dict[str, str | None]:
        """Read all phase artifacts for this loop.

        Returns:
            Dict mapping phase slug to artifact content (or None if missing).
        """
        result: dict[str, str | None] = {}

        for phase in _EXECUTION_PHASES:
            slug = _PHASE_SLUGS[phase]
            result[slug] = read_artifact(self.loop_id, slug)

        logger.debug(
            "evidence_pipeline.all_artifacts_read",
            loop_id=self.loop_id,
            found=sum(1 for v in result.values() if v is not None),
            total=len(result),
        )

        return result
