"""initial_schema_47_tables

Revision ID: e401bb5fd274
Revises: 2bed93fd1dd0
Create Date: 2026-06-02 07:05:25.328584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e401bb5fd274'
down_revision: Union[str, Sequence[str], None] = '2bed93fd1dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS agents")
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")
    op.execute("CREATE SCHEMA IF NOT EXISTS consent")
    op.execute("CREATE SCHEMA IF NOT EXISTS extensions")
    op.execute("CREATE SCHEMA IF NOT EXISTS financial")
    op.execute("CREATE SCHEMA IF NOT EXISTS memory")
    op.execute("CREATE SCHEMA IF NOT EXISTS ops")
    op.execute("CREATE SCHEMA IF NOT EXISTS persona")
    op.execute("CREATE SCHEMA IF NOT EXISTS projects")
    op.execute("CREATE SCHEMA IF NOT EXISTS security")
    op.execute("CREATE SCHEMA IF NOT EXISTS social")
    op.execute("CREATE SCHEMA IF NOT EXISTS surveillance")

    op.create_table('subagent_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.Text(), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('max_concurrency', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subagent_registry')),
    sa.UniqueConstraint('agent_name', name=op.f('uq_subagent_registry_agent_name')),
    schema='agents'
    )
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('principal', sa.Text(), nullable=False),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.Column('previous_hash', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_audit_trail')),
    schema='audit'
    )
    # Create TimescaleDB hypertable for audit_trail
    op.execute("SELECT create_hypertable('audit.audit_trail', 'occurred_at', chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE)")
    op.execute("SELECT add_retention_policy('audit.audit_trail', INTERVAL '1 year', if_not_exists => TRUE)")

    op.create_table('compliance_check',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_check')),
    schema='audit'
    )
    op.create_table('evidence_register',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('audit_event_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Text(), nullable=False),
    sa.Column('evidence_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_register')),
    schema='audit'
    )
    op.create_table('consent_ledger',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consent_type', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('evidence_hash', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_ledger')),
    schema='consent'
    )
    op.create_table('scope_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scope_name', sa.Text(), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=False),
    sa.Column('default_status', sa.Text(), nullable=False),
    sa.Column('data_domains_affected', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_registry')),
    sa.UniqueConstraint('scope_name', name=op.f('uq_scope_registry_scope_name')),
    schema='consent'
    )
    op.create_table('pgcrypto_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('extension_version', sa.Text(), nullable=False),
    sa.Column('default_algorithm', sa.Text(), server_default=sa.text("'aes-256-gcm'"), nullable=False),
    sa.Column('key_derivation_function', sa.Text(), server_default=sa.text("'pbkdf2'"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pgcrypto_config')),
    schema='extensions'
    )
    op.create_table('pgvector_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('extension_version', sa.Text(), nullable=False),
    sa.Column('default_index_type', sa.Text(), server_default=sa.text("'hnsw'"), nullable=False),
    sa.Column('hnsw_m', sa.Integer(), server_default=sa.text('16'), nullable=True),
    sa.Column('hnsw_ef_construction', sa.Integer(), server_default=sa.text('128'), nullable=True),
    sa.Column('hnsw_ef_search', sa.Integer(), server_default=sa.text('64'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pgvector_config')),
    schema='extensions'
    )
    op.create_table('timescaledb_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('extension_version', sa.Text(), nullable=False),
    sa.Column('default_chunk_interval', sa.Text(), server_default=sa.text("'7 days'"), nullable=True),
    sa.Column('compression_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('retention_default_days', sa.Integer(), server_default=sa.text('365'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timescaledb_config')),
    schema='extensions'
    )
    op.create_table('monthly_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_month', sa.Text(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('total_expense', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('api_cost_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_remaining', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports')),
    schema='financial'
    )
    op.create_table('optimization_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('optimization_type', sa.Text(), nullable=False),
    sa.Column('savings_estimate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_log')),
    schema='financial'
    )
    op.create_table('project_costs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('cost_category', sa.Text(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('billing_period', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_costs')),
    schema='financial'
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), server_default=sa.text("'IDR'"), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('api_model', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_transactions')),
    schema='financial'
    )
    # Create TimescaleDB hypertable for financial transactions
    op.execute("SELECT create_hypertable('financial.transactions', 'occurred_at', chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE)")
    op.execute("SELECT add_retention_policy('financial.transactions', INTERVAL '7 years', if_not_exists => TRUE)")

    op.create_table('emotional_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('intensity', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('subjective_experience', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotional_events')),
    schema='memory'
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('episode_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mood_at_start', sa.Text(), nullable=True),
    sa.Column('mood_at_end', sa.Text(), nullable=True),
    sa.Column('emotional_tone', sa.Text(), nullable=True),
    sa.Column('faiz_behavior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('importance', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('related_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'started_at', name=op.f('pk_episodes')),
    schema='memory'
    )
    # Create TimescaleDB hypertable for episodes
    op.execute("SELECT create_hypertable('memory.episodes', 'started_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE)")
    # Compression deferred - requires columnstore enablement first
    # HNSW index for episodes embedding
    op.execute("CREATE INDEX IF NOT EXISTS ix_episodes_embedding_hnsw ON memory.episodes USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128)")

    op.create_table('faiz_predictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prediction_type', sa.Text(), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('validated', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faiz_predictions')),
    schema='memory'
    )
    op.create_table('faiz_profile',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('sensitivity', sa.Text(), server_default=sa.text("'normal'"), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.8'), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('guinevere_note', sa.Text(), nullable=True),
    sa.Column('reveal_status', sa.Text(), server_default=sa.text("'never'"), nullable=True),
    sa.Column('access_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_accessed', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faiz_profile')),
    schema='memory'
    )
    op.create_table('inner_journal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood_self_report', sa.Text(), nullable=True),
    sa.Column('revealed_to_faiz', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('revealed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inner_journal')),
    schema='memory'
    )
    op.create_table('knowledge_graph',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('from_entity', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('to_entity', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('1.0'), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_graph')),
    schema='memory'
    )
    op.create_table('procedural_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('skill_name', sa.Text(), nullable=False),
    sa.Column('skill_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evolved_from', sa.UUID(), nullable=True),
    sa.Column('success_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evolved_from'], ['memory.procedural_skills.id'], name=op.f('fk_procedural_skills_evolved_from_procedural_skills'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedural_skills')),
    sa.UniqueConstraint('skill_name', name=op.f('uq_procedural_skills_skill_name')),
    schema='memory'
    )
    op.create_table('semantic_facts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object_val', sa.Text(), nullable=False),
    sa.Column('fact_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_episode', sa.UUID(), nullable=True),
    sa.Column('last_verified', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_count', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('contradicts_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_conflict', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('conflict_resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('guinevere_note', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_facts')),
    schema='memory'
    )
    # HNSW index for semantic_facts embedding
    op.execute("CREATE INDEX IF NOT EXISTS ix_semantic_facts_embedding_hnsw ON memory.semantic_facts USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128)")

    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_history')),
    schema='ops'
    )
    op.create_table('backup_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('backup_type', sa.Text(), nullable=False),
    sa.Column('backup_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_log')),
    schema='ops'
    )
    op.create_table('health_check',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_check')),
    schema='ops'
    )
    op.create_table('migration_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('migration_id', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('executed_by', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rollback_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('evidence_path', sa.Text(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_log')),
    sa.UniqueConstraint('migration_id', name=op.f('uq_migration_log_migration_id')),
    schema='ops'
    )
    op.create_table('drift_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drift_type', sa.Text(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_context', sa.Text(), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drift_log')),
    schema='persona'
    )
    op.create_table('mood_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mood', sa.Text(), nullable=False),
    sa.Column('intensity', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mood_history')),
    schema='persona'
    )
    op.create_table('persona_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('state_key', sa.Text(), nullable=False),
    sa.Column('state_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persona_state')),
    schema='persona'
    )
    op.create_table('punishment_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('violation_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('safe_word_triggered', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('safe_word_bypassed', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_punishment_log')),
    schema='persona'
    )
    op.create_table('reward_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reward_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('streak_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('awarded_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reward_log')),
    schema='persona'
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_agent', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    schema='projects'
    )
    op.create_table('access_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('principal', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=False),
    sa.Column('classification_bypassed', sa.Text(), nullable=True),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_log')),
    schema='security'
    )
    op.create_table('break_glass_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('principal', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('data_accessed', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('accessed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_break_glass_log')),
    schema='security'
    )
    op.create_table('secret_rotation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('secret_name', sa.Text(), nullable=False),
    sa.Column('rotation_type', sa.Text(), nullable=False),
    sa.Column('old_key_id', sa.Text(), nullable=True),
    sa.Column('new_key_id', sa.Text(), nullable=False),
    sa.Column('rotated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_rotation_log')),
    schema='security'
    )
    op.create_table('client_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('project_association', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.LargeBinary(), nullable=False),
    sa.Column('negotiation_notes', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_contacts')),
    schema='social'
    )
    op.create_table('social_map',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_contact_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_map')),
    schema='social'
    )
    op.create_table('confrontation_block_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('blocked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confrontation_block_log')),
    schema='surveillance'
    )
    op.create_table('device_registry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('device_type', sa.Text(), nullable=False),
    sa.Column('tailscale_ip', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_registry')),
    schema='surveillance'
    )
    op.create_table('task_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('task_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('5'), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.subagent_registry.id'], name=op.f('fk_task_queue_agent_id_subagent_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_queue')),
    schema='agents'
    )
    op.create_table('revocation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('revocation_type', sa.Text(), nullable=False),
    sa.Column('revoked_scope', sa.Text(), nullable=False),
    sa.Column('cascade_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consent.consent_ledger.id'], name=op.f('fk_revocation_log_consent_id_consent_ledger')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revocation_log')),
    schema='consent'
    )
    op.create_table('evidence_artifacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Text(), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['projects.tasks.id'], name=op.f('fk_evidence_artifacts_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts')),
    schema='projects'
    )
    op.create_table('loop_instances',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('loop_phase', sa.Text(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['projects.tasks.id'], name=op.f('fk_loop_instances_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loop_instances')),
    schema='projects'
    )
    op.create_table('communication_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['social.social_map.id'], name=op.f('fk_communication_log_contact_id_social_map'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_log')),
    schema='social'
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('raw_payload', sa.LargeBinary(), nullable=True),
    sa.Column('extracted_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['surveillance.device_registry.id'], name=op.f('fk_events_device_id_device_registry')),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_events')),
    schema='surveillance'
    )
    # Create TimescaleDB hypertable for surveillance events
    op.execute("SELECT create_hypertable('surveillance.events', 'occurred_at', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE)")
    op.execute("SELECT add_retention_policy('surveillance.events', INTERVAL '180 days', if_not_exists => TRUE)")
    # Compression policy deferred - requires columnstore enablement first

    op.create_table('ingestion_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('events_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['surveillance.device_registry.id'], name=op.f('fk_ingestion_log_device_id_device_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_log')),
    schema='surveillance'
    )
    op.create_table('execution_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.subagent_registry.id'], name=op.f('fk_execution_log_agent_id_subagent_registry')),
    sa.ForeignKeyConstraint(['task_id'], ['agents.task_queue.id'], name=op.f('fk_execution_log_task_id_task_queue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_log')),
    schema='agents'
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('loop_instance_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('classification', sa.Text(), server_default=sa.text("'Restricted'"), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('retention_class', sa.Text(), server_default=sa.text("'Long-Term Curated'"), nullable=False),
    sa.Column('retention_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('access_policy', sa.Text(), server_default=sa.text("'guinevere-core'"), nullable=False),
    sa.Column('encryption_profile', sa.Text(), server_default=sa.text("'envelope-AES-256-GCM'"), nullable=False),
    sa.Column('deletion_state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('key_id', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loop_instance_id'], ['projects.loop_instances.id'], name=op.f('fk_agent_tasks_loop_instance_id_loop_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tasks')),
    schema='projects'
    )


    # P3-002 manual TimescaleDB + pgvector patch.
    # Alembic autogenerate cannot infer hypertables or HNSW index DDL.
    op.execute("SELECT create_hypertable('audit.audit_trail', 'occurred_at', chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('financial.transactions', 'occurred_at', chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('memory.episodes', 'started_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE)")
    op.execute("SELECT create_hypertable('surveillance.events', 'occurred_at', chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_episodes_embedding_hnsw ON memory.episodes USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_semantic_facts_embedding_hnsw ON memory.semantic_facts USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 128)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_semantic_facts_source_episode ON memory.semantic_facts (source_episode)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_emotional_events_episode_id ON memory.emotional_events (episode_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_evidence_register_audit_event_id ON audit.evidence_register (audit_event_id)")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop HNSW indexes (created via op.execute in upgrade)
    op.execute("DROP INDEX IF EXISTS memory.ix_episodes_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS memory.ix_semantic_facts_embedding_hnsw")

    # Remove TimescaleDB hypertable policies
    op.execute("SELECT remove_retention_policy('memory.episodes', if_exists => TRUE)")
    op.execute("SELECT remove_retention_policy('surveillance.events', if_exists => TRUE)")
    op.execute("SELECT remove_retention_policy('financial.transactions', if_exists => TRUE)")
    op.execute("SELECT remove_retention_policy('audit.audit_trail', if_exists => TRUE)")

    op.drop_table('agent_tasks', schema='projects')
    op.drop_table('execution_log', schema='agents')
    op.drop_table('ingestion_log', schema='surveillance')
    op.drop_table('events', schema='surveillance')
    op.drop_table('communication_log', schema='social')
    op.drop_table('loop_instances', schema='projects')
    op.drop_table('evidence_artifacts', schema='projects')
    op.drop_table('revocation_log', schema='consent')
    op.drop_table('task_queue', schema='agents')
    op.drop_table('device_registry', schema='surveillance')
    op.drop_table('confrontation_block_log', schema='surveillance')
    op.drop_table('social_map', schema='social')
    op.drop_table('client_contacts', schema='social')
    op.drop_table('secret_rotation_log', schema='security')
    op.drop_table('break_glass_log', schema='security')
    op.drop_table('access_log', schema='security')
    op.drop_table('tasks', schema='projects')
    op.drop_table('reward_log', schema='persona')
    op.drop_table('punishment_log', schema='persona')
    op.drop_table('persona_state', schema='persona')
    op.drop_table('mood_history', schema='persona')
    op.drop_table('drift_log', schema='persona')
    op.drop_table('migration_log', schema='ops')
    op.drop_table('health_check', schema='ops')
    op.drop_table('backup_log', schema='ops')
    op.drop_table('alert_history', schema='ops')
    op.drop_table('semantic_facts', schema='memory')
    op.drop_table('procedural_skills', schema='memory')
    op.drop_table('knowledge_graph', schema='memory')
    op.drop_table('inner_journal', schema='memory')
    op.drop_table('faiz_profile', schema='memory')
    op.drop_table('faiz_predictions', schema='memory')
    op.drop_table('episodes', schema='memory')
    op.drop_table('emotional_events', schema='memory')
    op.drop_table('transactions', schema='financial')
    op.drop_table('project_costs', schema='financial')
    op.drop_table('optimization_log', schema='financial')
    op.drop_table('monthly_reports', schema='financial')
    op.drop_table('timescaledb_config', schema='extensions')
    op.drop_table('pgvector_config', schema='extensions')
    op.drop_table('pgcrypto_config', schema='extensions')
    op.drop_table('scope_registry', schema='consent')
    op.drop_table('consent_ledger', schema='consent')
    op.drop_table('evidence_register', schema='audit')
    op.drop_table('compliance_check', schema='audit')
    op.drop_table('audit_trail', schema='audit')
    op.drop_table('subagent_registry', schema='agents')
    # ### end Alembic commands ###
