#!/bin/bash
echo "=== DB STATE CHECK ==="
echo "Date: $(date -u -Iseconds)"
echo ""
echo "--- pgvector version ---"
docker exec guinevere-postgres psql -U guinevere -d guinevere -t -c "SELECT extname || ' ' || extversion FROM pg_extension WHERE extname = 'vector';"
echo ""
echo "--- Row counts ---"
docker exec guinevere-postgres psql -U guinevere -d guinevere -t -c "SELECT 'episodes' as tbl, count(*)::text as cnt FROM memory.episodes UNION ALL SELECT 'semantic_facts', count(*)::text FROM memory.semantic_facts;"
echo ""
echo "--- HNSW indexes ---"
docker exec guinevere-postgres psql -U guinevere -d guinevere -t -c "SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = 'memory' AND indexname LIKE '%hnsw%';"
echo ""
echo "--- Index sizes ---"
docker exec guinevere-postgres psql -U guinevere -d guinevere -t -c "SELECT c.relname::text AS index_name, pg_size_pretty(pg_relation_size(i.indexrelid))::text AS index_size FROM pg_index i JOIN pg_class c ON i.indexrelid = c.oid JOIN pg_namespace n ON c.relnamespace = n.oid JOIN pg_class t ON i.indrelid = t.oid WHERE n.nspname = 'memory' AND c.relname LIKE '%hnsw%';"
echo ""
echo "--- ef_search default ---"
docker exec guinevere-postgres psql -U guinevere -d guinevere -t -c "SHOW hnsw.ef_search;"
echo ""
echo "=== DB CHECK COMPLETE ==="