"""Monthly Cost Report — Automated FinOps report (P8-019).

Generates and posts a monthly cost report to the #cost-tracker Discord
channel on the 1st of each month.  Reads cost data from Redis DB5
and posts via a Discord webhook.

The scheduler is registered in the FastAPI lifespan (``guinevere/core/main.py``)
using APScheduler with a daily cron trigger.  The job checks whether
today is the 1st of the month before generating the report.

Graceful degradation: if Discord is unavailable, the report is logged
and the job will retry on the next scheduled cycle.
"""

from __future__ import annotations

import calendar
import os
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Final, Protocol, cast

import redis
import structlog

logger = structlog.get_logger()


class SchedulerProtocol(Protocol):
    """Minimal protocol for APScheduler's ``AsyncIOScheduler``.

    Covers only the methods needed by the lifespan manager:
    ``start()`` and ``shutdown()``.
    """

    def start(self) -> None:
        """Start the scheduler."""
        ...

    def shutdown(self, wait: bool = True) -> None:
        """Shut down the scheduler."""
        ...

# ── Constants ───────────────────────────────────────────────────────────────

EMBED_COLOR: Final[int] = 0x6B21A8
"""Purple embed colour for FinOps reports."""

FOOTER_TEXT: Final[str] = "Generated by Guinevere FinOps"
"""Footer text for the monthly report embed."""

WEBHOOK_ENV: Final[str] = "DISCORD_COST_TRACKER_WEBHOOK"
"""Environment variable name for the cost-tracker channel webhook URL."""

DEFAULT_MONTHLY_CAP: Final[float] = 30.0
"""Default monthly cap when none is configured in Redis."""


# ── Timezone ────────────────────────────────────────────────────────────────

WIB: Final[timezone] = timezone(timedelta(hours=7))
"""Asia/Bangkok/WIB timezone offset (+07:00)."""


# ── Data Types ──────────────────────────────────────────────────────────────


@dataclass(frozen=True)
class ModelCostEntry:
    """Per-model cost entry for the report.

    Attributes:
        model: Model name.
        cost: Total cost in USD.
    """

    model: str
    cost: float


@dataclass(frozen=True)
class ToolCostEntry:
    """Per-tool cost entry for the report.

    Attributes:
        tool: Tool name.
        cost: Total cost in USD.
    """

    tool: str
    cost: float


@dataclass(frozen=True)
class MonthlyReportData:
    """Deterministic data for a monthly cost report.

    Attributes:
        month_label: Human-readable month label (e.g. ``"June 2026"``).
        total_spend: Total spend for the reported month.
        previous_month_spend: Total spend for the previous month.
        model_breakdown: Per-model cost entries.
        tool_breakdown: Per-tool cost entries.
        daily_trend: Last 7 days of daily costs as (label, cost) tuples.
        budget_cap: Configured monthly budget cap.
        budget_remaining: Remaining budget after current spend.
        budget_percent_used: Percentage of budget used.
    """

    month_label: str
    total_spend: float
    previous_month_spend: float
    model_breakdown: tuple[ModelCostEntry, ...]
    tool_breakdown: tuple[ToolCostEntry, ...]
    daily_trend: tuple[tuple[str, float], ...]
    budget_cap: float
    budget_remaining: float
    budget_percent_used: float


# ── Helpers ─────────────────────────────────────────────────────────────────


def _safe_float(raw: object) -> float:
    """Convert a Redis value to float, returning 0.0 on failure."""
    if raw is None:
        return 0.0
    try:
        return float(str(raw))
    except (ValueError, TypeError):
        return 0.0


def _format_currency(amount: float) -> str:
    """Format a float as a currency string."""
    return f"${amount:.4f}"


def _get_redis_client() -> redis.Redis:
    """Create a Redis client for cost data retrieval.

    Returns:
        A ``redis.Redis`` instance connected to DB5.
    """
    from guinevere.core.services.cost_tracker import CostTracker

    return cast(redis.Redis, cast(object, CostTracker().redis))


def _get_month_label(d: date) -> str:
    """Return a human-readable month label like ``"June 2026"``.

    Args:
        d: A date within the target month.

    Returns:
        Month name and year.
    """
    return d.strftime("%B %Y")


def _get_previous_month(d: date) -> date:
    """Return the 1st of the previous month.

    Args:
        d: Reference date.

    Returns:
        A date representing the 1st of the previous month.
    """
    first_of_current = d.replace(day=1)
    return first_of_current - timedelta(days=1)


def _get_monthly_total(r: redis.Redis, target_month: str) -> float:
    """Read the monthly total from Redis for a given YYYY-MM key.

    Args:
        r: Redis client.
        target_month: Month string in ``YYYY-MM`` format.

    Returns:
        Total cost for the month.
    """
    key = f"cost:monthly:{target_month}"
    return _safe_float(r.get(key))


def _get_model_breakdown_for_month(r: redis.Redis) -> list[ModelCostEntry]:
    """Get per-model cost breakdown from Redis (current running totals).

    Args:
        r: Redis client.

    Returns:
        List of ModelCostEntry sorted by cost descending.
    """
    models: list[ModelCostEntry] = []
    try:
        for key in r.scan_iter(match="cost:by_model:*"):
            model_name = key.removeprefix("cost:by_model:")
            cost = _safe_float(r.get(key))
            if cost > 0:
                models.append(ModelCostEntry(model=model_name, cost=cost))
    except Exception:
        logger.warning("monthly_report_model_scan_failed")
    models.sort(key=lambda e: e.cost, reverse=True)
    return models


def _get_tool_breakdown_for_month(r: redis.Redis) -> list[ToolCostEntry]:
    """Get per-tool cost breakdown from Redis for the current month.

    Scans all ``tool:cost:*`` keys to aggregate per-tool totals.

    Args:
        r: Redis client.

    Returns:
        List of ToolCostEntry sorted by cost descending.
    """
    tool_totals: dict[str, float] = {}
    try:
        for key in r.scan_iter(match="tool:cost:*"):
            suffix = key.removeprefix("tool:cost:")
            if suffix.startswith("total:"):
                continue
            parts = suffix.rsplit(":", 1)
            if len(parts) != 2:
                continue
            tool_name = parts[0]
            cost = _safe_float(r.get(key))
            if cost > 0:
                tool_totals[tool_name] = tool_totals.get(tool_name, 0.0) + cost
    except Exception:
        logger.warning("monthly_report_tool_scan_failed")

    entries = [
        ToolCostEntry(tool=name, cost=cost)
        for name, cost in tool_totals.items()
    ]
    entries.sort(key=lambda e: e.cost, reverse=True)
    return entries


def _get_daily_trend(r: redis.Redis, ref: date, days: int = 7) -> list[tuple[str, float]]:
    """Get daily cost trend for the last N days.

    Args:
        r: Redis client.
        ref: Reference date.
        days: Number of days to look back.

    Returns:
        List of (date_label, cost) in chronological order.
    """
    trend: list[tuple[str, float]] = []
    for i in range(days - 1, -1, -1):
        day = ref - timedelta(days=i)
        key = f"cost:daily:{day.isoformat()}"
        cost = _safe_float(r.get(key))
        trend.append((day.strftime("%b %d"), cost))
    return trend


# ── Report Builder ──────────────────────────────────────────────────────────


def build_monthly_report(
    *,
    ref_date: date | None = None,
) -> MonthlyReportData:
    """Build deterministic monthly report data from Redis.

    Reads cost data from Redis DB5 and constructs a complete report
    with total spend, per-model breakdown, per-tool breakdown, daily
    trend, budget status, and trend vs previous month.

    Args:
        ref_date: Override reference date for determinism (e.g. in tests).
                  Defaults to ``date.today()``.

    Returns:
        A fully populated ``MonthlyReportData``.
    """
    today = ref_date if ref_date is not None else date.today()
    month_str = today.strftime("%Y-%m")
    month_label = _get_month_label(today)

    r = _get_redis_client()

    # Current month total
    total_spend = _get_monthly_total(r, month_str)
    # Also check cost:current_month as fallback
    current_month_running = _safe_float(r.get("cost:current_month"))
    if current_month_running > total_spend:
        total_spend = current_month_running

    # Previous month
    prev_month_date = _get_previous_month(today)
    prev_month_str = prev_month_date.strftime("%Y-%m")
    previous_month_spend = _get_monthly_total(r, prev_month_str)

    # Per-model breakdown
    model_entries = _get_model_breakdown_for_month(r)

    # Per-tool breakdown
    tool_entries = _get_tool_breakdown_for_month(r)

    # Daily trend (last 7 days)
    daily_trend = _get_daily_trend(r, today)

    # Budget
    cap_raw = r.get("budget:monthly_cap")
    budget_cap = _safe_float(cap_raw) if cap_raw is not None else DEFAULT_MONTHLY_CAP
    budget_remaining = max(budget_cap - total_spend, 0.0)
    budget_percent_used = (total_spend / budget_cap * 100) if budget_cap > 0 else 0.0

    return MonthlyReportData(
        month_label=month_label,
        total_spend=total_spend,
        previous_month_spend=previous_month_spend,
        model_breakdown=tuple(model_entries),
        tool_breakdown=tuple(tool_entries),
        daily_trend=tuple(daily_trend),
        budget_cap=budget_cap,
        budget_remaining=budget_remaining,
        budget_percent_used=budget_percent_used,
    )


# ── Report Formatter ────────────────────────────────────────────────────────


def format_report_content(report: MonthlyReportData) -> str:
    """Format the monthly report as a Discord message string.

    Produces a rich-text message suitable for posting to a channel.
    Uses Discord markdown formatting.

    Args:
        report: The monthly report data.

    Returns:
        A formatted string ready for Discord posting.
    """
    lines: list[str] = []

    # Header
    lines.append(f"## \U0001f4ca Monthly Cost Report \u2014 {report.month_label}")
    lines.append("")

    # Summary
    trend_arrow = "\U0001f4c8" if report.total_spend >= report.previous_month_spend else "\U0001f4c9"
    trend_diff = report.total_spend - report.previous_month_spend
    trend_sign = "+" if trend_diff >= 0 else ""

    lines.append(f"**Total Spend:** {_format_currency(report.total_spend)}")
    lines.append(
        f"**vs Previous Month:** {_format_currency(report.previous_month_spend)} "
        f"({trend_arrow} {trend_sign}{_format_currency(trend_diff)})"
    )
    lines.append(f"**Budget Cap:** {_format_currency(report.budget_cap)}")
    lines.append(
        f"**Budget Remaining:** {_format_currency(report.budget_remaining)} "
        f"({report.budget_percent_used:.1f}% used)"
    )
    lines.append("")

    # Per-model table
    if report.model_breakdown:
        lines.append("### \U0001f916 Per-Model Breakdown")
        lines.append("```")
        lines.append(f"{'Model':<25} {'Cost':>10}")
        lines.append("-" * 37)
        for entry in report.model_breakdown:
            model_display = entry.model[:25]
            lines.append(f"{model_display:<25} {_format_currency(entry.cost):>10}")
        lines.append("```")
        lines.append("")
    else:
        lines.append("### \U0001f916 Per-Model Breakdown")
        lines.append("No model costs recorded this month.")
        lines.append("")

    # Per-tool table
    if report.tool_breakdown:
        lines.append("### \U0001f527 Per-Tool Breakdown")
        lines.append("```")
        lines.append(f"{'Tool':<25} {'Cost':>10}")
        lines.append("-" * 37)
        for entry in report.tool_breakdown:
            tool_display = entry.tool[:25]
            lines.append(f"{tool_display:<25} {_format_currency(entry.cost):>10}")
        lines.append("```")
        lines.append("")
    else:
        lines.append("### \U0001f527 Per-Tool Breakdown")
        lines.append("No tool costs recorded this month.")
        lines.append("")

    # Daily trend
    if report.daily_trend:
        lines.append("### \U0001f4c8 7-Day Trend")
        lines.append("```")
        for label, cost in report.daily_trend:
            bar_len = int(min(cost * 10, 20)) if cost > 0 else 0
            bar = "\u2588" * max(bar_len, 1) if cost > 0 else "\u2591"
            lines.append(f"{label:<8} {bar:<20} {_format_currency(cost)}")
        lines.append("```")
        lines.append("")

    # Footer
    lines.append(f"\u2014 *{FOOTER_TEXT}*")

    return "\n".join(lines)


# ── Discord Webhook Posting ─────────────────────────────────────────────────


async def post_report_to_discord(report: MonthlyReportData) -> bool:
    """Post the monthly report to the #cost-tracker Discord channel.

    Uses a webhook URL from the ``DISCORD_COST_TRACKER_WEBHOOK``
    environment variable.  Returns ``True`` on success, ``False`` on
    failure (with error logged).

    Args:
        report: The monthly report data.

    Returns:
        ``True`` if the report was posted successfully, ``False`` otherwise.
    """
    webhook_url = os.environ.get(WEBHOOK_ENV)
    if not webhook_url:
        logger.warning(
            "monthly_report_no_webhook",
            env_var=WEBHOOK_ENV,
        )
        return False

    content = format_report_content(report)

    try:
        import httpx

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                webhook_url,
                json={"content": content},
            )
            response.raise_for_status()

        logger.info(
            "monthly_report_posted",
            month=report.month_label,
            total_spend=report.total_spend,
        )
        return True

    except Exception as exc:
        logger.error(
            "monthly_report_post_failed",
            error=str(exc),
            month=report.month_label,
        )
        return False


# ── Scheduler Job ───────────────────────────────────────────────────────────


async def monthly_report_job() -> None:
    """APScheduler job that runs daily and posts on the 1st of each month.

    Checks whether today is the 1st of the month.  If so, builds the
    report for the previous month and posts it to Discord.  If Discord
    is unavailable, the error is logged and the job will retry on the
    next scheduled cycle.
    """
    today = date.today()

    # Only run on the 1st of the month
    if today.day != 1:
        logger.debug("monthly_report_not_first_of_month", day=today.day)
        return

    # Report covers the previous month
    prev_month_date = _get_previous_month(today)
    logger.info(
        "monthly_report_generating",
        month=prev_month_date.strftime("%Y-%m"),
    )

    try:
        report = build_monthly_report(ref_date=prev_month_date)
        posted = await post_report_to_discord(report)

        if not posted:
            logger.warning(
                "monthly_report_post_skipped",
                reason="webhook unavailable or post failed",
            )
    except Exception:
        logger.exception("monthly_report_job_failed")


# ── Scheduler Registration ──────────────────────────────────────────────────


def register_monthly_report_scheduler() -> SchedulerProtocol:
    """Create and configure the APScheduler for the monthly report job.

    Creates an ``AsyncIOScheduler`` with a daily cron trigger that calls
    ``monthly_report_job``.  The scheduler is NOT started here — the
    caller (``main.py`` lifespan) is responsible for calling
    ``scheduler.start()`` and ``scheduler.shutdown()``.

    Returns:
        A configured ``AsyncIOScheduler`` instance with the job added.
    """
    from apscheduler.schedulers.asyncio import AsyncIOScheduler
    from apscheduler.triggers.cron import CronTrigger

    scheduler = AsyncIOScheduler()

    # Run daily at 08:00 WIB (01:00 UTC)
    scheduler.add_job(
        monthly_report_job,
        trigger=CronTrigger(hour=1, minute=0),
        id="monthly_cost_report",
        name="Monthly Cost Report",
        replace_existing=True,
    )

    logger.info("monthly_report_scheduler_registered")
    return cast(SchedulerProtocol, cast(object, scheduler))
