"""add_search_vector_do_not_recall

Revision ID: 65f863220922
Revises: e401bb5fd274
Create Date: 2026-06-02 13:58:43.080071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65f863220922'
down_revision: Union[str, Sequence[str], None] = 'e401bb5fd274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(summary, '')), 'B') || setweight(to_tsvector('english', coalesce(raw_content, '')), 'D')", ), nullable=True), schema='memory')
    op.add_column('episodes', sa.Column('do_not_recall', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='memory')
    op.create_index('ix_episodes_search_vector_gin', 'episodes', ['search_vector'], unique=False, schema='memory', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episodes_search_vector_gin', table_name='episodes', schema='memory', postgresql_using='gin')
    op.drop_column('episodes', 'do_not_recall', schema='memory')
    op.drop_column('episodes', 'search_vector', schema='memory')
    # ### end Alembic commands ###
