import pathlib; out = pathlib.Path('docs/setup-evidence/hermes-phase2-discord/batch-plan-phase-2-discord.md'); lines = []
def A(s): lines.append(s)
def S(): lines.append('')
def H(t): lines.append('## ' + t); lines.append('')
def H3(t): lines.append('### ' + t); lines.append('')
def B(t): lines.append('**' + t + '**')
def HR(): lines.append('---'); lines.append('')
def LI(t): lines.append('- ' + t)
def QU(t): lines.append('> ' + t)
def BL(s): lines.append(''); lines.append('`' + s); lines.append('`'); lines.append('')
A("# Phase 2 Batch Plan -- Discord Gateway Migration")
S()
QU("**Date:** 2026-06-04 | **Version:** 1.0 | **Author:** Guinevere (Sisyphus-Junior)")
QU("**Status:** Planning | **Evidence Root:** docs/setup-evidence/hermes-phase2-discord/")
QU("**ADR:** adr/ADR-035-hermes-migration.md | **Phase 1:** DEPLOYED + AUDITED (PASS)")
S()
HR()
H("1. Scope and Objectives")
A("Migrate Guinevere Discord gateway from custom discord.py bot.py stack to Hermes Agent v0.15.2 native gateway. This is the largest and highest-risk phase of the 7-phase Hermes migration (ADR-035). 4 waves, 24 atomic steps, 48-hour shadow mode mandatory before cutover.")
S()
